### ISSUE TITLE
DLNA not discoverable with Plugin 2.0.0.0 and JF 10.9.3

### ISSUE THREAD

**Issue by iwch** [jellyfin/jellyfin-plugin-dlna#55]
Hi, I'm trying to use the DLNA functionality of Jellyfin in a reverse proxy + ipvlan/macvlan setup in Docker. Specifically, I'm running nginx as a reverse proxy to access my instance via the internet, which means that I do not want to use host networking for the Jellyfin container (which is running the official `jellyfin/jellyfin:10.9.3` image). I also want to use DLNA to play stuff on the local network. This was working fairly well in 10.8.13, using a macvlan docker network. Unfortunately, 10.9.x releases seem to have broken it, and I'd appreciate some help to get it working again. My machine information and the relevant bits of my docker-compose.yml are below:

- Host OS: Ubuntu 22.04
- CPU/GPU: Ryzen 5650g 
- Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1
- docker-compose.yml:
```
version: "3.8"
services:
  jellyfin:
    image: jellyfin/jellyfin:10.9.3
    container_name: jellyfin
    devices:
      - /dev/dri
      - /dev/kfd
    group_add:
      - video
      - 109
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
    restart: "unless-stopped"
    security_opt:
      - seccomp:unconfined
    ipc: host
    shm_size: 16G
    ports:
      - "8096:8096"
      - "8920:8920"
      - "1900:1900/udp"
    networks:
     - jellyfin_vlan
     - default
volumes:
  jellyfin-config:
    driver: local
  jellyfin-cache:
    driver: local
networks:
  jellyfin_vlan:
    driver: macvlan
    driver_opts:
      parent: enp3s0
    ipam:
      config:
        - subnet: 192.168.1.1/24

```

It seems like my jellyfin container is assigned 192.168.1.2 in this setup. I can ping 192.168.1.2 from a different machine without problem, and it even shows up in my router's management console. However, no DLNA client seems to be capable of finding it. A quick `docker-compose logs jellyfin | grep -i dlna` suggests that the DLNA plugin is correctly finding the 192.168.1.2 address associated with the macvlan interface:

```
jellyfin               | [23:59:33] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Dlna.Playback, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/DLNA_2.0.0.0/Jellyfin.Plugin.Dlna.Playback.dll
jellyfin               | [23:59:33] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Dlna, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/DLNA_2.0.0.0/Jellyfin.Plugin.Dlna.dll
jellyfin               | [23:59:33] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Rssdp, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/DLNA_2.0.0.0/Rssdp.dll
jellyfin               | [23:59:33] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Dlna.Model, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/DLNA_2.0.0.0/Jellyfin.Plugin.Dlna.Model.dll
jellyfin               | [23:59:36] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: DLNA 2.0.0.0
jellyfin               | [23:59:36] [INF] [1] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 127.0.0.1
jellyfin               | [23:59:36] [INF] [1] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 172.31.0.7
jellyfin               | [23:59:36] [INF] [1] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 192.168.1.2
```

As a final remark, all networking and DLNA plugin settings are untouched in the Jellyfin web GUI.
